# Generated by Django 3.1 on 2020-08-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=30)),
                ('school', models.IntegerField(max_length=4)),
                ('group', models.IntegerField(verbose_name=4)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('questions', models.TextField(blank=True, max_length=255)),
            ],
        ),
    ]
