# Generated by Django 3.1 on 2020-09-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=30)),
                ('school', models.IntegerField()),
                ('group', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('questions', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logos')),
                ('school_name', models.CharField(max_length=30)),
                ('week_day', models.CharField(max_length=20)),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
            ],
        ),
    ]
