# Generated by Django 3.1 on 2020-08-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='group',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='school',
            field=models.IntegerField(),
        ),
    ]
