# Generated by Django 3.1 on 2020-09-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200904_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympian',
            name='picture',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(upload_to='schools'),
        ),
    ]
