# Generated by Django 3.1 on 2020-09-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200904_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympian',
            name='achievements',
            field=models.CharField(default='', max_length=500),
        ),
    ]
