# Generated by Django 3.1 on 2020-09-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_olympian_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='ending_time',
        ),
        migrations.RemoveField(
            model_name='school',
            name='starting_time',
        ),
        migrations.AddField(
            model_name='school',
            name='evening_ending_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='evening_starting_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='morning_ending_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='morning_starting_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
