# Generated by Django 3.1 on 2020-09-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200905_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='week_day',
        ),
        migrations.AddField(
            model_name='school',
            name='evening_week_day',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='morning_week_day',
            field=models.CharField(default='', max_length=20),
        ),
    ]
